### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by huangli6** [Mkild/dental-admin#1]
![image](https://user-images.githubusercontent.com/68462569/232840990-547cbc81-7877-495d-93f8-457d731f48ec.png)
这个没看懂，请问有了这个页面后的下一步操作是什么呀

**Comment by Mkild** [comment]
能看到这个页面说明项目已经成功启动了，这个页面只是用来提示的而不是在这个页面操作。。项目成功启动后，剩下就是根据接口文档调用接口。**Token**和**JWT**你不熟悉的话建议自行去搜索引擎搜索了解。
另外，后端项目的问题请移步到后端项目仓库（[https://github.com/Mkild/dental-admin-api](url)）提问。
